// Native shell for the Fittin' app (Capacitor 8, "Mode C": the binary loads the live site).
// Why a remote shell and not a static export: see docs/native/01-decision.md.
//
// Plain CommonJS on purpose: the site is plain JS, and a .ts config would drag TypeScript into a
// project that has none.

const isDev = process.env.NODE_ENV === "development";
const devUrl = process.env.CAPACITOR_SERVER_URL;

// Live reload only. A release binary that points at a laptop ships a white screen to every user,
// so refuse to build one.
if (devUrl && !isDev) {
  throw new Error("CAPACITOR_SERVER_URL is set outside development. Unset it (or run with NODE_ENV=development).");
}

const START_URL = devUrl || "https://fittin.be/app";

// The bundled offline page must retry THIS build's server: a dev build its laptop, a store build
// fittin.be. It can't ask Capacitor (on that local page getServerUrl() is the app's own local
// origin), so hand it the URL here. This file is loaded by every `cap sync` / `cap copy`, right
// before native-shell/ is copied into the app. Generated, so gitignored.
try {
  require("fs").writeFileSync(
    require("path").join(__dirname, "native-shell", "start-url.js"),
    `// Generated by capacitor.config.js — do not edit.\nwindow.FITTIN_START = ${JSON.stringify(START_URL)};\n`
  );
} catch { /* read-only checkout: offline.html falls back to fittin.be */ }

// Brand indigo: launch screen, splash, webview background and the /app welcome screen all share
// it, so a cold start goes launch → splash → welcome without a single white frame.
const LAUNCH_BG = "#22194F";

/** @type {import('@capacitor/cli').CapacitorConfig} */
const config = {
  appId: "be.fittin.app",
  // Typographic apostrophe: matches the wordmark, and unlike ' it needs no escaping in
  // Android's strings.xml.
  appName: "Fittin’",
  // Only offline.html lives here: the app itself is served by fittin.be.
  webDir: "native-shell",
  backgroundColor: LAUNCH_BG,
  loggingBehavior: isDev ? "debug" : "none",
  ios: {
    contentInset: "never", // full-bleed webview; the site pads itself with --sat/--sab
    allowsLinkPreview: false, // no long-press link previews: a web tell
    // The site detects the app from this (inline script in app/layout.jsx) without going dynamic.
    appendUserAgent: "FittinApp/1",
    backgroundColor: LAUNCH_BG,
  },
  android: {
    appendUserAgent: "FittinApp/1",
    allowMixedContent: isDev,
    backgroundColor: LAUNCH_BG,
  },
  server: {
    url: START_URL,
    cleartext: isDev,
    // Hosts the webview may navigate to itself. Everything else opens in the system browser
    // (and our click handler sends it to an in-app Safari/Custom Tab first). Stripe Checkout is
    // the one third party that must run inside: a payment that jumps to Safari lands back on the
    // website, not in the app.
    allowNavigation: ["fittin.be", "www.fittin.be", "checkout.stripe.com", "hooks.stripe.com"],
    // Bundled in webDir. Shown when a navigation fails (cold start offline) instead of a blank page.
    errorPath: "offline.html",
  },
  plugins: {
    SplashScreen: {
      // Hidden from JS as soon as the first page has painted (components/native/NativeBoot).
      // This duration is only the ceiling for when JS never runs (offline, server down).
      // 10 s, not 4: a first launch on a slow connection took >12 s to paint /boeken in the
      // simulator, and with a 4 s ceiling that showed an empty indigo screen in between.
      launchShowDuration: 10000,
      launchAutoHide: true,
      launchFadeOutDuration: 200,
      backgroundColor: LAUNCH_BG,
      showSpinner: false,
      androidScaleType: "CENTER_CROP",
    },
    // Android 15+ is edge-to-edge; Capacitor injects --safe-area-inset-* for the CSS tokens.
    SystemBars: { insetsHandling: "css" },
    PushNotifications: { presentationOptions: ["badge", "sound", "alert"] },
    // "native" shrinks the webview while the keyboard is up. This is a scrolling document site with
    // sticky bottom bars (booking confirm, workout player): they then sit on top of the keyboard
    // for free. The playbook's "never resize" rule protects WebGL maps; there are none here.
    Keyboard: { resize: "native" },
  },
};

module.exports = config;
